name: openpanel_flutter
description: "Openpanel is an open-source alternative to Mixpanel that combines the power of Mixpanel with the ease of Plausible. This package is not officially maintained by the Openpanel team."
version: 0.2.0
homepage: https://github.com/stevenosse/openpanel_flutter.git
topics: 
  - analytics

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.7
  logger: ^2.5.0
  package_info_plus: ^8.1.1
  referrer: ^1.1.0
  shared_preferences: ^2.3.3
  device_user_agent: ^0.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
