name: openpanel_flutter
description: "Openpanel is an open-source alternative to Mixpanel that combines the power of Mixpanel with the ease of Plausible. This package is not officially maintained by the Openpanel team."
version: 0.2.1
homepage: https://github.com/stevenosse/openpanel_flutter
topics: 
  - analytics

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  device_info_plus: ^12.2.0
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  logger: ^2.5.0
  package_info_plus: ^9.0.0
  meta: ^1.15.0
  referrer: ^1.1.0
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
