name: Code Verification

on: [push, pull_request]

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # required
      - uses: flutterings/dart-package-analyzer@v1
        with:
          flutter_version: 3.22.0
